version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    depends_on:
      - db
